import "./panel-log.js";
import { createTaintState } from "../lib/agent/trust/taint.js";
import { defaultSettings } from "../lib/storage.js";

const state = {
  settings: defaultSettings(),
  tab: null,
  pack: null,
  share: true,
  messages: [],
  image: null,
  busy: false,
  view: "chat",
  abort: null,
  skills: [],
  skillsMetaReady: false,
  skillsMetaLoading: false,
  skillsMetaError: "",
  sessionId: null,
  windowId: null,
  sessionCreatedAt: null,
  sessionPages: [],
  histQuery: "",
  run: null,
  stopIntent: null,
  taskGroupId: null,
  transcribe: null,
  recordAbort: null,
  workAbort: null,
  interpret: null,
  siCapture: null,
  originalAudioOn: true,
  library: { configured: false, granted: false, name: "" },
  textProviderUi: { adding: false, editingId: "", query: "", addModel: {}, msg: "", err: "" },
  skillFolder: { configured: false, granted: false, name: "", count: 0 },
  nativeHost: { ok: false, checked: false },
  sessionHitlOverride: null,
  hitlApprovedOrigins: new Set(),
  injectionSuspected: null,
  capsule: null,
  taint: createTaintState(),
  refLabel: null,
  dubPlaying: false,
  activeToolDomains: new Set(),
  currentClipMsg: null,
  activeRecallClippings: [],
  dismissedRecallUrls: new Set(),
  review: {
    type: "daily",
    date: Date.now(),
    selectedClippingIds: new Set(),
    activeClippings: [],
    activeReview: null,
    generating: false,
    abort: null,
    lastPeriodKey: null,
  },
  mediaExpanded: true,
  toolsExpanded: false,
  tasksExpanded: true,
  chatRef: null,
  videoSummary: null,
  mediaTab: null,
  mediaPack: null,
  pageRevision: 0,
  dismissedPage: null,
};


export {
  state,
};
